# Generated by Django 2.0.13 on 2019-03-03 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.AutoField(db_column='adh_id', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='adh_nom', max_length=100)),
                ('prenom', models.CharField(db_column='adh_auteur', max_length=100)),
                ('mail', models.TextField(db_column='adh_contenu', null=True)),
                ('created_at', models.DateTimeField(db_column='adh_create_at', default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='adh_image')),
            ],
            options={
                'verbose_name_plural': 'Adherent',
                'verbose_name': 'Adherent',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(db_column='art_id', primary_key=True, serialize=False)),
                ('titre', models.CharField(db_column='art_titre', max_length=100)),
                ('contenu', models.TextField(db_column='art_contenu', null=True)),
                ('created_at', models.DateTimeField(db_column='art_date', default=django.utils.timezone.now, verbose_name='Date de parution')),
            ],
            options={
                'verbose_name_plural': 'articles',
                'verbose_name': 'article',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(db_column='mem_id', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='mem_nom', max_length=100)),
                ('prenom', models.CharField(db_column='mem_auteur', max_length=100)),
                ('mail', models.TextField(db_column='mem_contenu', null=True)),
                ('description', models.TextField(db_column='mem_description', null=True)),
                ('titre', models.CharField(blank=True, db_column='mem_titre', max_length=100, null=True)),
                ('created_at', models.DateTimeField(db_column='rmem_create_at', default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='img')),
            ],
            options={
                'verbose_name_plural': 'Membre',
                'verbose_name': 'Membre',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.AutoField(db_column='nle_id', primary_key=True, serialize=False)),
                ('titre', models.CharField(db_column='nle_titre', max_length=100)),
                ('contenu', models.TextField(db_column='nle_contenu', null=True)),
                ('created_at', models.DateTimeField(db_column='nle_date', default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('auteur', models.ForeignKey(db_column='nle_auteur', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Membre')),
            ],
            options={
                'verbose_name_plural': 'NewsLetters',
                'verbose_name': 'NewsLetter',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(db_column='pay_id', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='pay_nom', max_length=100)),
                ('created_at', models.DateTimeField(db_column='pay_create_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_column='pay_date_update', default=django.utils.timezone.now)),
                ('representant', models.ManyToManyField(db_column='pay_representant', to='blog.Membre')),
            ],
            options={
                'verbose_name_plural': 'Pays',
                'verbose_name': 'Pays',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(db_column='art_auteur', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Membre'),
        ),
    ]
