# Generated by Django 2.0.13 on 2019-03-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='mail',
            field=models.CharField(db_column='mem_mail', max_length=100, null=True),
        ),
    ]
