# Generated by Django 2.0.13 on 2019-03-03 22:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190303_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambassadeur',
            fields=[
                ('id', models.AutoField(db_column='amb_id', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='amb_nom', max_length=100)),
                ('prenom', models.CharField(db_column='amb_auteur', max_length=100)),
                ('mail', models.CharField(db_column='amb_mail', max_length=100, null=True)),
                ('description', models.TextField(db_column='amb_description', null=True)),
                ('created_at', models.DateTimeField(db_column='amb_create_at', default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, upload_to='img')),
            ],
            options={
                'verbose_name_plural': 'Ambassadeurs',
                'verbose_name': 'Ambassadeur',
                'ordering': ['nom'],
            },
        ),
    ]
