# Generated by Django 2.0.13 on 2019-03-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ambassadeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadeur',
            name='mail',
            field=models.CharField(blank=True, db_column='amb_mail', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='mail',
            field=models.CharField(blank=True, db_column='mem_mail', max_length=100, null=True),
        ),
    ]
