# Generated by Django 2.0.13 on 2019-12-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190904_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambassadeur',
            name='description_en',
            field=models.TextField(db_column='amb_description_en', null=True),
        ),
        migrations.AddField(
            model_name='ambassadeur',
            name='description_fr',
            field=models.TextField(db_column='amb_description_fr', null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='description_en',
            field=models.TextField(db_column='mem_description_en', null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='description_fr',
            field=models.TextField(db_column='mem_description_fr', null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='titre_en',
            field=models.CharField(blank=True, db_column='mem_titre_en', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='titre_fr',
            field=models.CharField(blank=True, db_column='mem_titre_fr', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='contenu_en',
            field=models.TextField(db_column='nle_contenu_en', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='contenu_fr',
            field=models.TextField(db_column='nle_contenu_fr', null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='titre_en',
            field=models.CharField(db_column='nle_titre_en', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='titre_fr',
            field=models.CharField(db_column='nle_titre_fr', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pays',
            name='nom_en',
            field=models.CharField(db_column='pay_nom_en', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pays',
            name='nom_fr',
            field=models.CharField(db_column='pay_nom_fr', max_length=100, null=True),
        ),
    ]
